{
    'name': 'CGA Income & Expenditure Report Data',
    'version': '15.0.1.0',
    'summary': 'CGA Income & Expenditure Report Data',
    'sequence': 4,
    'description': """ CGA Income & Expenditure Report Data """,
    'category': 'Accounting/Accounting',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'account',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/account_division_data.xml',
        'data/cga_income_expenditure_report_data.xml',
        'data/cga_refined_coconut_oil_data.xml',
        'data/cga_detergents_data.xml',
        'data/cga_cosmetics_data.xml',
        'data/cga_margarines_data.xml',
        'data/cga_crude_coconut_oil_data.xml',
        'data/cga_bath_soap_data.xml',
        'views/menu_action.xml',
        'views/menu_item.xml',
        'views/account_division.xml',
        'views/account_account.xml',
    ],
    'assets': {},
    'demo': [],
    'installable': True,
    'application': False,
    'auto_install': False,

}
